#!/bin/bash
### BEGIN INIT INFO
# Provides:          hastcope
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: none
# Description:       none
#
### END INIT INFO

APPNAME=hastcope
USER=root
HASTCOPE_DIR=/var/hastcope
ACTIVATE=$HASTCOPE_DIR/venv/bin/activate
APPMODULE=app:app
DAEMON=gunicorn
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/$DAEMON.log


. /lib/lsb/init-functions


if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi


case "$1" in
  start)
        log_daemon_msg "Starting deferred execution scheduler" "$APPNAME"
        source $ACTIVATE
        $DAEMON --daemon --pid=$PIDFILE --user=$USER --log-file=$LOGFILE --chdir $HASTCOPE_DIR -c $HASTCOPE_DIR/gunicorn.config.py $APPMODULE
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution scheduler" "APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0

